/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccessibilityRouteImport } from './routes/_authenticated/accessibility'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAppearanceRouteImport } from './routes/_authenticated/appearance'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AuthenticatedBroadcastRouteImport } from './routes/_authenticated/broadcast'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedLanguageRouteImport } from './routes/_authenticated/language'
import { Route as AuthenticatedListsRouteImport } from './routes/_authenticated/lists'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStarredRouteImport } from './routes/_authenticated/starred'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated/storage'
import { Route as AuthenticatedWallpaperRouteImport } from './routes/_authenticated/wallpaper'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as AuthenticatedChatsIdRouteImport } from './routes/_authenticated/chats.$id'
import { Route as AuthenticatedGroupIdRouteImport } from './routes/_authenticated/group.$id'
import { Route as AuthenticatedProfileIdRouteImport } from './routes/_authenticated/profile.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessibilityRoute =
  AuthenticatedAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppearanceRoute = AuthenticatedAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBroadcastRoute = AuthenticatedBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLanguageRoute = AuthenticatedLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsRoute = AuthenticatedListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStarredRoute = AuthenticatedStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWallpaperRoute = AuthenticatedWallpaperRouteImport.update({
  id: '/wallpaper',
  path: '/wallpaper',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunitiesRoute = AuthenticatedCommunitiesRouteImport.update({ id: '/communities', path: '/communities', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({ id: '/channels', path: '/channels', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIdRoute = AuthenticatedChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupIdRoute = AuthenticatedGroupIdRouteImport.update({
  id: '/group/$id',
  path: '/group/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIdRoute = AuthenticatedProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/appearance': typeof AuthenticatedAppearanceRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/broadcast': typeof AuthenticatedBroadcastRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/language': typeof AuthenticatedLanguageRoute
  '/lists': typeof AuthenticatedListsRoute
  '/new': typeof AuthenticatedNewRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/starred': typeof AuthenticatedStarredRoute
  '/status': typeof AuthenticatedStatusRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/wallpaper': typeof AuthenticatedWallpaperRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/group/$id': typeof AuthenticatedGroupIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/appearance': typeof AuthenticatedAppearanceRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/broadcast': typeof AuthenticatedBroadcastRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/language': typeof AuthenticatedLanguageRoute
  '/lists': typeof AuthenticatedListsRoute
  '/new': typeof AuthenticatedNewRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/starred': typeof AuthenticatedStarredRoute
  '/status': typeof AuthenticatedStatusRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/wallpaper': typeof AuthenticatedWallpaperRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/group/$id': typeof AuthenticatedGroupIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accessibility': typeof AuthenticatedAccessibilityRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/appearance': typeof AuthenticatedAppearanceRoute
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_authenticated/broadcast': typeof AuthenticatedBroadcastRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/language': typeof AuthenticatedLanguageRoute
  '/_authenticated/lists': typeof AuthenticatedListsRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/starred': typeof AuthenticatedStarredRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/wallpaper': typeof AuthenticatedWallpaperRoute
  '/_authenticated/chats/$id': typeof AuthenticatedChatsIdRoute
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/group/$id': typeof AuthenticatedGroupIdRoute
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accessibility'
    | '/account'
    | '/ai'
    | '/appearance'
    | '/blocked'
    | '/broadcast'
    | '/calls'
    | '/contacts'
    | '/help'
    | '/invite'
    | '/language'
    | '/lists'
    | '/new'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/starred'
    | '/status'
    | '/storage'
    | '/wallpaper'
    | '/chats/$id'
    | '/communities'
    | '/channels'
    | '/group/$id'
    | '/profile/$id'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accessibility'
    | '/account'
    | '/ai'
    | '/appearance'
    | '/blocked'
    | '/broadcast'
    | '/calls'
    | '/contacts'
    | '/help'
    | '/invite'
    | '/language'
    | '/lists'
    | '/new'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/starred'
    | '/status'
    | '/storage'
    | '/wallpaper'
    | '/chats/$id'
    | '/communities'
    | '/channels'
    | '/group/$id'
    | '/profile/$id'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accessibility'
    | '/_authenticated/account'
    | '/_authenticated/ai'
    | '/_authenticated/appearance'
    | '/_authenticated/blocked'
    | '/_authenticated/broadcast'
    | '/_authenticated/calls'
    | '/_authenticated/contacts'
    | '/_authenticated/help'
    | '/_authenticated/invite'
    | '/_authenticated/language'
    | '/_authenticated/lists'
    | '/_authenticated/new'
    | '/_authenticated/notifications'
    | '/_authenticated/privacy'
    | '/_authenticated/settings'
    | '/_authenticated/starred'
    | '/_authenticated/status'
    | '/_authenticated/storage'
    | '/_authenticated/wallpaper'
    | '/_authenticated/chats/$id'
    | '/_authenticated/communities'
    | '/_authenticated/channels'
    | '/_authenticated/group/$id'
    | '/_authenticated/profile/$id'
    | '/_authenticated/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accessibility': {
      id: '/_authenticated/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AuthenticatedAccessibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appearance': {
      id: '/_authenticated/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AuthenticatedAppearanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broadcast': {
      id: '/_authenticated/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AuthenticatedBroadcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/language': {
      id: '/_authenticated/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof AuthenticatedLanguageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists': {
      id: '/_authenticated/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthenticatedListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/starred': {
      id: '/_authenticated/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof AuthenticatedStarredRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallpaper': {
      id: '/_authenticated/wallpaper'
      path: '/wallpaper'
      fullPath: '/wallpaper'
      preLoaderRoute: typeof AuthenticatedWallpaperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/$id': {
      id: '/_authenticated/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group/$id': {
      id: '/_authenticated/group/$id'
      path: '/group/$id'
      fullPath: '/group/$id'
      preLoaderRoute: typeof AuthenticatedGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessibilityRoute: typeof AuthenticatedAccessibilityRoute
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAppearanceRoute: typeof AuthenticatedAppearanceRoute
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
  AuthenticatedBroadcastRoute: typeof AuthenticatedBroadcastRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedLanguageRoute: typeof AuthenticatedLanguageRoute
  AuthenticatedListsRoute: typeof AuthenticatedListsRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStarredRoute: typeof AuthenticatedStarredRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedWallpaperRoute: typeof AuthenticatedWallpaperRoute
  AuthenticatedChatsIdRoute: typeof AuthenticatedChatsIdRoute
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedGroupIdRoute: typeof AuthenticatedGroupIdRoute
  AuthenticatedProfileIdRoute: typeof AuthenticatedProfileIdRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessibilityRoute: AuthenticatedAccessibilityRoute,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAppearanceRoute: AuthenticatedAppearanceRoute,
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
  AuthenticatedBroadcastRoute: AuthenticatedBroadcastRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedLanguageRoute: AuthenticatedLanguageRoute,
  AuthenticatedListsRoute: AuthenticatedListsRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStarredRoute: AuthenticatedStarredRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedWallpaperRoute: AuthenticatedWallpaperRoute,
  AuthenticatedChatsIdRoute: AuthenticatedChatsIdRoute,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedGroupIdRoute: AuthenticatedGroupIdRoute,
  AuthenticatedProfileIdRoute: AuthenticatedProfileIdRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
